### ISSUE TITLE
Problem downloading the metadata

### ISSUE THREAD

**Issue by HatemMS2012** [mjhucla/P-Multimodal-Dataset-Toolbox#1]
Hi,

Thank you for the nice work.
I am trying to download the metadata files using `bash download_meta.sh`

However, I am getting the following error:

> --2016-11-29 10:35:30--  http://www.cs.jhu.edu/~jhmao/open_source_data/pinterest_multimodal_dataset/pinterest_multimodal_2016_v1.tar.gz
Resolving www.cs.jhu.edu (www.cs.jhu.edu)... 128.220.13.76
Connecting to www.cs.jhu.edu (www.cs.jhu.edu)|128.220.13.76|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-11-29 10:35:30 ERROR 403: Forbidden.
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Hope you can help me with this issue.

Best,

**Comment by zhaobozb** [comment]
Me too.

**Comment by mjhucla** [comment]
Thanks for pointing it out. Can you try it again now?

**Comment by HatemMS2012** [comment]
it is working now. Thanks

**Comment by oujago** [comment]
Sorry, I got "405 Not Allowed httpserver". Is there anything wrong?

**Comment by mjhucla** [comment]
I just tried. The meta file data should be able to access. Could you try it again?

**Comment by oujago** [comment]
So sorry, because I'm in China. I can download the data after I use VPN. So I just deleted.
So thank you!
